echo "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
echo ${RECIPE_DIR}
echo ${SRC_DIR}
echo ${PREFIX}
echo "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"

cmake ${RECIPE_DIR}/../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=${PREFIX}
cmake --build . --target install
