version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_install:
      - cmake -B ./build -DCMAKE_INSTALL_PREFIX=./libparallelproj_install
      - cmake --build ./build --target install
      - ls -l ./libparallelproj_install/lib
      #- export PARALLELPROJ_C_LIB=./libparallelproj_install/lib/libparallelproj_c.so
      # the PARALLELPROJ_C_LIB environment variable must be defiend in the RTD project dashboard
      - ls -l ${PARALLELPROJ_C_LIB} 

conda:
  environment: docs/environment.yml
# This part is necessary otherwise the project is not built
python:
  install:
    - method: pip
      path: .

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py
