version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
  environ:
    PARALLELPROJ_C_LIB: "${READTHEDOCS_REPOSITORY_PATH}/libparallelproj_install/lib/libparallelproj_c.so"
  jobs:
    post_install:
      - cmake -B ./build -DCMAKE_INSTALL_PREFIX=./libparallelproj_install
      - cmake --build ./build --target install
      - ls -l ./libparallelproj_install/lib
      - echo ${PARALLELPROJ_C_LIB} 
      - ls -l ${PARALLELPROJ_C_LIB} 

conda:
  environment: docs/environment.yml
# This part is necessary otherwise the project is not built
python:
  install:
    - method: pip
      path: .

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py
