name: readthedocs
channels:
  - conda-forge
dependencies:
  - sphinx>=7.0
  - sphinx_rtd_theme
  - sphinx-gallery
  - sphinx-design
  - sphinx-copybutton
  - sphinxcontrib-bibtex
  - libparallelproj
  - pytorch
  - scipy
