name: readthedocs
channels:
  - conda-forge
dependencies:
  - python < 3.13
  - sphinx>=7.0
  - sphinx_rtd_theme
  - sphinx-gallery
  - sphinx-design
  - sphinx-copybutton
  - sphinxcontrib-bibtex
  - libparallelproj
  - pytorch
  - scipy
  
