name: readthedocs
channels:
  - conda-forge
dependencies:
  - python
  - sphinx>=7.0
  - sphinx-rtd-theme
  - sphinx-gallery
  - sphinx-design
  - sphinx-copybutton
  - sphinxcontrib-bibtex
  - matplotlib
  - array-api-compat
  - pytorch
  - scipy
  - cmake
