name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - master
    push:
      tags:
        - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12 # Specify the Python version compatible with your environment
          environment-file: docs/environment.yml # Use your environment.yml to install dependencies
          activate-environment: readthedocs # Name from environment.yml

      - name: Install Sphinx multiversion extension
        run: conda install -c conda-forge sphinx-multiversion

      - name: Build documentation
        run: sphinx-multiversion docs/source _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
